stages:
  - docker-build

dockerbuild:
  stage: docker-build
  image: node:11
  script:
    - apt-get update
    - apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update
    - apt-get install docker-ce docker-ce-cli containerd.io -y
    - docker ps
    - apt-get install python3-pip -y
    - pip3 install awscli
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - aws eks update-kubeconfig --name chm-test-default --region eu-central-1 --role-arn arn:aws:iam::540467641217:role/chm.test.default.eks_Admin
    - kubectl get ns
    - npm run build
    - npm run docker:build